server:
  port: 80
spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://bj-cdb-3xrlmzai.sql.tencentcdb.com:63037/sicmed_slaver_ychz?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Sicmed123
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000


#mybatis
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
logging:
  level:
    root: debug