http:
  port: 80
server:
  port: 443
  ssl:
    key-store: classpath:www.qlxlm.com.jks
    key-store-password: 123456
    key-store-type: jks
spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://bj-cdb-3xrlmzai.sql.tencentcdb.com:63037/sicmed_slaver_ychz?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    url: jdbc:mysql://192.168.20.114:3306/sicmed_slaver_ychz?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Sicmed123
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    lettuce:
      pool:
        MaxTotal: 50
        minIdle: 1
        maxWaitMillis: 5000
        maxIdle: 5
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
    redis-a:
      database: 0
      hostName: 192.168.20.100
      password:
      port: 6379
      timeout: 5000
    redis-b:
      database: 1
      hostName: ${spring.redis.redis-a.hostName}
      port: ${spring.redis.redis-a.port}
      password: ${spring.redis.redis-a.password}
      timeout: ${spring.redis.redis-a.timeout}
    redis-c:
      database: 2
      hostName: ${spring.redis.redis-a.hostName}
      port: ${spring.redis.redis-a.port}
      password: ${spring.redis.redis-a.password}
      timeout: ${spring.redis.redis-a.timeout}
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${img.location}, file:${img.location}/dist, file:${img.location}/dist/assets, file:${img.location}/app
  servlet:
    multipart:
      max-request-size: 1048576000
      max-file-size: 1048576000
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
logging:
  level:
    root: debug
img:
  location: d:/mypicture
#  location: /home/mypicture
#static:
#  resource: /root/web
#  windows:
#  linux: /root/web
#腾讯云服务配置信息
qcloud:
  appid: 1400091903
  secretkey: 5aec8ead3060edd9278730217587053d
  smssign: 腾讯云